# Generated by Django 3.0.1 on 2019-12-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=45000)),
                ('testcaseno', models.IntegerField(default=0)),
                ('samplein', models.CharField(default='', max_length=45000)),
                ('sampleout', models.CharField(default='', max_length=45000)),
                ('tc1', models.CharField(max_length=1000)),
                ('tc2', models.CharField(max_length=1000)),
                ('tc3', models.CharField(max_length=1000)),
                ('tc1_sol', models.CharField(max_length=1000)),
                ('tc2_sol', models.CharField(max_length=1000)),
                ('tc3_sol', models.CharField(max_length=1000)),
            ],
        ),
    ]
